FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
ARG API_PROJECT=Auth.Wiedersehen
ARG API_PROJECT_FILE=$API_PROJECT/$API_PROJECT.csproj
ARG SHARED_PROJECT=Auth.Wiedersehen.Shared
ARG SHARED_PROJECT_FILE=$SHARED_PROJECT/$SHARED_PROJECT.csproj

WORKDIR /src

COPY $API_PROJECT_FILE ./$API_PROJECT/
COPY $SHARED_PROJECT_FILE ./$SHARED_PROJECT/
RUN dotnet restore $API_PROJECT_FILE

COPY $API_PROJECT/ ./$API_PROJECT/
COPY $SHARED_PROJECT/ ./$SHARED_PROJECT/
RUN dotnet build $API_PROJECT_FILE -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
ARG API_PROJECT=Auth.Wiedersehen
ARG API_PROJECT_FILE=$API_PROJECT/$API_PROJECT.csproj

RUN dotnet publish $API_PROJECT_FILE -c $BUILD_CONFIGURATION --self-contained --runtime linux-musl-arm64 -o /app/publish

FROM alpine:latest AS final
RUN apk add --no-cache libgcc libstdc++ icu-libs
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["./Auth.Wiedersehen"]
