FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
ARG ADMIN_API_PROJECT=Skoruba.Duende.IdentityServer.Admin.Api
ARG ADMIN_API_PROJECT_FILE=$ADMIN_API_PROJECT/$ADMIN_API_PROJECT.csproj

WORKDIR /src

COPY Directory.Packages.props ./
COPY $ADMIN_API_PROJECT_FILE ./$ADMIN_API_PROJECT/
COPY Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared/Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared.csproj ./Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared/
COPY Skoruba.Duende.IdentityServer.Admin.EntityFramework.PostgreSQL/Skoruba.Duende.IdentityServer.Admin.EntityFramework.PostgreSQL.csproj ./Skoruba.Duende.IdentityServer.Admin.EntityFramework.PostgreSQL/
COPY Skoruba.Duende.IdentityServer.Shared/Skoruba.Duende.IdentityServer.Shared.csproj ./Skoruba.Duende.IdentityServer.Shared/
RUN dotnet restore $ADMIN_API_PROJECT_FILE

COPY $ADMIN_API_PROJECT/ ./$ADMIN_API_PROJECT/
COPY Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared/ ./Skoruba.Duende.IdentityServer.Admin.EntityFramework.Shared/
COPY Skoruba.Duende.IdentityServer.Admin.EntityFramework.PostgreSQL/ ./Skoruba.Duende.IdentityServer.Admin.EntityFramework.PostgreSQL/
COPY Skoruba.Duende.IdentityServer.Shared/ ./Skoruba.Duende.IdentityServer.Shared/
RUN dotnet build $ADMIN_API_PROJECT_FILE -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
ARG ADMIN_API_PROJECT=Skoruba.Duende.IdentityServer.Admin.Api
ARG ADMIN_API_PROJECT_FILE=$ADMIN_API_PROJECT/$ADMIN_API_PROJECT.csproj

RUN dotnet publish $ADMIN_API_PROJECT_FILE -c $BUILD_CONFIGURATION --self-contained --runtime linux-musl-arm64 -o /app/publish

FROM alpine:latest AS final
ARG ADMIN_API_PROJECT=Skoruba.Duende.IdentityServer.Admin.Api
RUN apk add --no-cache libgcc libstdc++ icu-libs gettext krb5-libs
WORKDIR /app
COPY --from=publish /app/publish .
COPY $ADMIN_API_PROJECT/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
